### PR TITLE
simplify repackaging function (cosmetic change)

### PR DESCRIPTION
**Pull request by matteolimberto-da**
Not sure what you think about the following cosmetic change @lucianojoublanc-da, 

- it removes an extra iteration of fmaps
- I changed the name of the function to make it (in my opinion) a bit more descriptive

I would like to add a comment to the code explaining that the function "repackages" the recursive type sending the Either to the front. What is the accepted practice for it: `-- |` at beginning of function or `-- ^` after the function definition?

### CODE REVIEW

**Review by lucianojoublanc-da — APPROVED** [review]
I think this is somewhat subjective; personally I don't think it makes it easier to understand, but I'm not against this change. Perhaps worth considering taking out `tsidE` and making it top-level with comments to explain what it does.

**Comment by matteolimberto-da** [comment]
Thanks for the feedback. I went for 'factor', as you suggested. Let me know how you find it.

**Comment by matteolimberto-da** [comment]
This PR is now outdated due to the recent commits on the `fix-scale` branch. Feel free to ignore it for now.

**Comment by matteolimberto-da** [comment]
Closing this PR as this is now outdated

**Pull request closed without merging**
